In [4]:
import numpy as np
import math
import os.path
import csv
import glob
import tensorflow as tf
import h5py as h5py
from keras.preprocessing import image
from keras.applications.inception_v3 import InceptionV3, preprocess_input
from keras.models import Model, load_model

import imageio
import matplotlib.pyplot as plt
from mlxtend.image import extract_face_landmarks

def eye_aspect_ratio(eye):
	A = distance.euclidean(eye[1], eye[5])
	B = distance.euclidean(eye[2], eye[4])
	C = distance.euclidean(eye[0], eye[3])
	ear = (A + B) / (2.0 * C)
	return ear
def mouth_aspect_ratio(mouth):
    A = distance.euclidean(mouth[14], mouth[18])
    C = distance.euclidean(mouth[12], mouth[16])
    mar = (A ) / (C)
    return mar

def circularity(eye):
    A = distance.euclidean(eye[1], eye[4])
    radius  = A/2.0
    Area = math.pi * (radius ** 2)
    p = 0
    p += distance.euclidean(eye[0], eye[1])
    p += distance.euclidean(eye[1], eye[2])
    p += distance.euclidean(eye[2], eye[3])
    p += distance.euclidean(eye[3], eye[4])
    p += distance.euclidean(eye[4], eye[5])
    p += distance.euclidean(eye[5], eye[0])
    return 4 * math.pi * Area /(p**2)


def mouth_over_eye(eye):
    ear = eye_aspect_ratio(eye)
    mar = mouth_aspect_ratio(eye)
    mouth_eye = mar/ear
    return mouth_eye

def getFrame(sec):
    start = 1800
    vidcap.set(cv2.CAP_PROP_POS_MSEC, start + sec*1000)
    hasFrames,image = vidcap.read()
    return hasFrames, image


# main program
from scipy.spatial import distance
import cv2
data = []
labels = []
for j in [60]:
  for i in [0]:
    vidcap = cv2.VideoCapture (r'C:\Users\dell\Desktop\AI\Alert_Participant_1.mp4')
    sec = 0
    frameRate = 1
    success, image  = getFrame(sec)
    count = 0
    print( success)
    print(image)
    while success and count < 240: 
          landmarks = extract_face_landmarks(image)
          if sum(sum(landmarks)) != 0:
              count += 1
              data.append(landmarks)
              labels.append([i])
              sec = sec + frameRate
              sec = round(sec, 2)
              success, image = getFrame(sec)
              print(count)
          else:  
              sec = sec + frameRate
              sec = round(sec, 2)
              success, image = getFrame(sec)
              print("not detected")

#print( success)
#print(image)
import numpy as np
data = np.array(data)
labels = np.array(labels)

features = []
for d in data:
  eye = d[36:68]
  ear = eye_aspect_ratio(eye)
  mar = mouth_aspect_ratio(eye)
  cir = circularity(eye)
  mouth_eye = mouth_over_eye(eye)
  features.append([ear, mar, cir, mouth_eye])

features = np.array(features)

Using TensorFlow backend.


True
[[[117 125 124]
  [117 125 124]
  [117 125 124]
  ...
  [101 109 108]
  [100 108 107]
  [100 108 107]]

 [[117 125 124]
  [117 125 124]
  [117 125 124]
  ...
  [101 109 108]
  [101 109 108]
  [101 109 108]]

 [[117 125 124]
  [117 125 124]
  [117 125 124]
  ...
  [104 112 111]
  [104 112 111]
  [104 112 111]]

 ...

 [[ 10  20  19]
  [ 23  33  32]
  [ 41  51  48]
  ...
  [ 71 100 136]
  [ 71 100 136]
  [ 71 100 136]]

 [[ 16  26  25]
  [ 32  42  41]
  [ 49  59  58]
  ...
  [ 71 100 136]
  [ 71 100 136]
  [ 71 100 136]]

 [[ 24  34  33]
  [ 38  48  47]
  [ 52  62  61]
  ...
  [ 71 100 136]
  [ 70  99 135]
  [ 70  99 135]]]
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29
30
31
32
33
34
35
36
37
38
39
40
41
42
43
44
45
46
47
48
49
50
51
52
53
54
55
56
57
58
59
60
61
62
63
64
65
66
67
68
69
70
71
72
73
74
75
76
77
78
79
80
81
82
83
84
85
86
87
88
89
90
91
92
93
94
95
96
97
98
99
100
101
102
103
104
105
106
107
108
109
110
111
112
113
114
115
116
117
118
1

In [5]:
data.shape

(240, 68, 2)

In [6]:
labels.shape

(240, 1)

In [7]:
features.shape

(240, 4)

In [8]:
#saving landmarks of each frame
np.save(open('Alert_Participant_1_Data.npy', 'wb'),data)

#saving the features in .npy file and creating CSV file for that
np.save(open('Alert_Participant_1_Features.npy', 'wb'),features)
np.savetxt("Alert_Particpant_1_Features.csv", features, delimiter = ",")

#saving the labels in .npy file and creating CSV file for that
np.save(open('Alert_Participant_1_Labels.npy', 'wb'),labels)
np.savetxt("Alert_Participant_1_Labels.csv", labels, delimiter = ",")

In [10]:
landmarks

array([[ 411,  818],
       [ 406,  859],
       [ 405,  901],
       [ 409,  942],
       [ 419,  981],
       [ 437, 1017],
       [ 468, 1045],
       [ 508, 1064],
       [ 557, 1072],
       [ 610, 1070],
       [ 657, 1059],
       [ 702, 1042],
       [ 735, 1013],
       [ 757,  976],
       [ 770,  933],
       [ 779,  888],
       [ 785,  842],
       [ 439,  758],
       [ 459,  732],
       [ 489,  721],
       [ 523,  719],
       [ 554,  729],
       [ 610,  730],
       [ 648,  723],
       [ 687,  726],
       [ 721,  742],
       [ 742,  772],
       [ 579,  765],
       [ 577,  782],
       [ 574,  799],
       [ 571,  817],
       [ 532,  863],
       [ 550,  865],
       [ 567,  867],
       [ 587,  867],
       [ 607,  867],
       [ 472,  781],
       [ 490,  763],
       [ 514,  761],
       [ 535,  780],
       [ 514,  785],
       [ 490,  787],
       [ 629,  784],
       [ 653,  766],
       [ 678,  770],
       [ 698,  789],
       [ 677,  794],
       [ 652,